# Config file for automatic testing at travis-ci.com
language: python
python: 2.7

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=flake8
  # add environments for every test in tox.ini

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - pip install tox
  - pip install -r requirements.txt
  - pip install -r dev-requirements.txt

# command to run tests, e.g. python setup.py test
script: 
  - tox -e $TOX_ENV

after_success:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coverage run --source=unicampi setup.py test
  - coveralls
